name: Continuous Deployment (EC2)

on:
  push:
    branches:
      - main
      - ci-cd
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v4
      - name: Set up Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'
      - name: Build Project
        run:  ./gradlew clean bootJar
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker image
        run:  docker build -t mnr1332/adpro-aws-ec2 .
      - name: Publish image to Dockerhub
        run: docker push mnr1332/adpro-aws-ec2::latest

  deploy:
    needs:  build
    runs-on: [udehnih-course-aws-ec2]
    steps:
      - name: Pull image from Dockerhub
        run:  docker pull mnr1332/adpro-aws-ec2::latest
      - name: Delete old container
        run:  docker rm -f udehnih-course
      - name: Run docker container
        run:  docker run -d -p 8080:8080 --name udehnih-course mnr1332/adpro-aws-ec2::latest
